/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bachboss.mangadownloader.gui.control;

/**
 *
 * @author bach
 */
public class PannelLog extends javax.swing.JPanel {

    /**
     * Creates new form PannelLog
     */
    public PannelLog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlAll = new javax.swing.JTabbedPane();
        pnlException = new javax.swing.JTabbedPane();
        pnlNotify = new javax.swing.JTabbedPane();

        jTabbedPane1.addTab("tab1", pnlAll);
        jTabbedPane1.addTab("tab1", pnlException);
        jTabbedPane1.addTab("tab1", pnlNotify);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane pnlAll;
    private javax.swing.JTabbedPane pnlException;
    private javax.swing.JTabbedPane pnlNotify;
    // End of variables declaration//GEN-END:variables
}
